In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              582 non-null    object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    object
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 163.8+ KB

In [117]:
df.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Gender                          0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             386
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

In [118]:
# df['Employee_Name'] = df['Employee_Name'].str.replace(',', ' ', regex=False)

In [119]:
df['Department'].unique()

array(['Production       ', 'IT/IS', 'Software Engineering',
       'Admin Offices', 'Sales', 'Executive Office'], dtype=object)

In [120]:
df_strings = df.select_dtypes(['object'])

In [121]:
df_strings.columns

Index(['Employee_Name', 'Position', 'State', 'DOB', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'DateofHire',
       'DateofTermination', 'TermReason', 'EmploymentStatus', 'Department',
       'ManagerName', 'RecruitmentSource', 'PerformanceScore',
       'LastPerformanceReview_Date'],
      dtype='object')

In [122]:
columns = ['Employee_Name', 'Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason', 'EmploymentStatus', 'Department',
       'ManagerName', 'RecruitmentSource', 'PerformanceScore']

In [123]:
# for col in columns:
#     print('\n')
#     print(col)
#     print('-'*50)
#     print(df[col].unique())

## Strip

In [124]:
'''
strip() -> remove both side white space
lstrip() -> only remove left side white space
rstrip() -> only remove right side white space
'''

'\nstrip() -> remove both side white space\nlstrip() -> only remove left side white space\nrstrip() -> only remove right side white space\n'

In [125]:
# df['Employee_Name'] = df['Employee_Name'].str.strip()

In [126]:
for col in columns:
    df[col] = df[col].str.strip()

In [127]:
df['DOB'] = pd.to_datetime(df['DOB'])

In [128]:
df['DateofTermination'] = pd.to_datetime(df['DateofTermination'])

In [129]:
df['DateofTermination']

0            NaT
1     2016-06-16
2     2012-09-24
3            NaT
4     2016-09-06
         ...
577   2016-09-06
578          NaT
579          NaT
580          NaT
581          NaT
Name: DateofTermination, Length: 582, dtype: datetime64[ns]

# Feature Engineering

In [130]:
df['DOB'].max()

Timestamp('1992-08-17 00:00:00')

In [131]:
df['Birth_Year'] = df['DOB'].dt.year

In [132]:
df['Birth_Month'] = df['DOB'].dt.month
df['Birth_Day'] = df['DOB'].dt.day

In [133]:
df['Birth_Month_Name'] = df['DOB'].dt.month_name()
df['Birth_Day_Name'] = df['DOB'].dt.day_name()

In [134]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,Birth_Year,Birth_Month,Birth_Day,Birth_Month_Name,Birth_Day_Name
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,5,0,1/17/2019,0,1,1983,7,10,July,Sunday
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,3,6,2/24/2016,0,17,1975,5,5,May,Monday
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,3,0,5/15/2012,0,3,1988,9,19,September,Monday
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,5,0,1/3/2019,0,15,1988,9,27,September,Tuesday
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,4,0,2/1/2016,0,2,1989,9,8,September,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,4,0,2/1/2016,0,2,1989,9,8,September,Friday
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,5,0,1/7/2019,0,15,1977,5,22,May,Sunday
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,3,4,1/2/2019,0,19,1979,5,24,May,Thursday
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,4,0,2/25/2019,0,19,1983,2,18,February,Friday
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,3,0,1/25/2019,0,4,1970,2,11,February,Wednesday

In [135]:
# split(find, n(number of columns)=index, expand=False(default)/True)
# name = df['Employee_Name'].str.split(' ', n=2, expand=True)
# name

In [136]:
last_first = df['Employee_Name'].str.split(',', n=1, expand=True)
last_first

              0             1
0      Adinolfi     Wilson  K
1      Ait Sidi   Karthikeyan
2    Akinkuolie         Sarah
3        Alagbe         Trina
4      Anderson         Carol
..          ...           ...
577    Anderson         Carol
578    Anderson         Linda
579    Andreola         Colby
580      Athwal           Sam
581   Bachiochi         Linda

[582 rows x 2 columns]

In [137]:
first_middle = last_first[1].str.strip().str.split(' ', n=1, expand=True)
first_middle

               0     1
0         Wilson     K
1    Karthikeyan  None
2          Sarah  None
3          Trina  None
4          Carol  None
..           ...   ...
577        Carol  None
578        Linda  None
579        Colby  None
580          Sam  None
581        Linda  None

[582 rows x 2 columns]

In [138]:
df['First_Name'] = first_middle[0]
df['Middle_Name'] = first_middle[1]
df['Last_Name'] = last_first[0]

In [139]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,DaysLateLast30,Absences,Birth_Year,Birth_Month,Birth_Day,Birth_Month_Name,Birth_Day_Name,First_Name,Middle_Name,Last_Name
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,0,1,1983,7,10,July,Sunday,Wilson,K,Adinolfi
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,0,17,1975,5,5,May,Monday,Karthikeyan,None,Ait Sidi
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,0,3,1988,9,19,September,Monday,Sarah,None,Akinkuolie
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,0,15,1988,9,27,September,Tuesday,Trina,None,Alagbe
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,0,2,1989,9,8,September,Friday,Carol,None,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,0,2,1989,9,8,September,Friday,Carol,None,Anderson
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,0,15,1977,5,22,May,Sunday,Linda,None,Anderson
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,0,19,1979,5,24,May,Thursday,Colby,None,Andreola
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,0,19,1983,2,18,February,Friday,Sam,None,Athwal
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,0,4,1970,2,11,February,Wednesday,Linda,None,Bachiochi

In [142]:
df['HispanicLatino'].unique()

array(['no', 'yes'], dtype=object)

In [143]:
# df['HispanicLatino'] = df['HispanicLatino'].str.capitalize()
# df['HispanicLatino'] = df['HispanicLatino'].str.lower()

In [8]:
df['Department'] = df['Department'].str.strip()
df['Department'].unique()

array(['Production', 'IT/IS', 'Software Engineering', 'Admin Offices',
       'Sales', 'Executive Office'], dtype=object)

In [10]:
data = {
    'Production': 0, 
    'IT/IS': 1, 
    'Software Engineering': 2, 
    'Admin Offices': 3,
    'Sales': 4, 
    'Executive Office': 5
}
df['Department_EncodeId'] = df['Department'].map(data)

In [12]:
# df[['Department', 'Department_EncodeId']]

In [24]:
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

In [14]:
le = LabelEncoder()

In [15]:
df['Le_department'] = le.fit_transform(df['Department'])

In [22]:
# df[['Department', 'Department_EncodeId', 'Le_department']]

In [21]:
print(df['Department'].unique())
print(f'Map: {df['Department_EncodeId'].unique()}')
print(f'LE: {df['Le_department'].unique()}')

['Production' 'IT/IS' 'Software Engineering' 'Admin Offices' 'Sales'
 'Executive Office']
Map: [0 1 2 3 4 5]
LE: [3 2 5 0 4 1]

In [28]:
df['PerformanceScore'].unique()

array(['Exceeds', 'Fully Meets', 'Needs Improvement', 'PIP'], dtype=object)

In [29]:
features = ['Salary', 'Le_department', 'EngagementSurvey', 'EmpSatisfaction']
X = df[features]
Y = df['PerfScoreID']

In [41]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.3, random_state=42
)

In [36]:
scaler = StandardScaler()
# fit_transform -> fit - learn (calculation) + transform - implement (formula implementation)
X_train_scale = scaler.fit_transform(X_train)
# transformo -> implement
X_test_scale = scaler.transform(X_test)

In [37]:
# X_test_scale

In [38]:
mm = MinMaxScaler()
X_train_mm = mm.fit_transform(X_train)
X_test_mm = mm.transform(X_test)

In [40]:
X_test_mm

array([[9.55279244e-03, 6.00000000e-01, 1.00000000e+00, 7.50000000e-01],
       [3.56175841e-02, 4.00000000e-01, 8.19587629e-01, 5.00000000e-01],
       [2.32711909e-02, 6.00000000e-01, 3.04123711e-01, 5.00000000e-01],
       [2.88616986e-02, 6.00000000e-01, 8.96907216e-01, 1.00000000e+00],
       [2.06990945e-02, 6.00000000e-01, 1.00000000e+00, 1.00000000e+00],
       [2.97196150e-02, 6.00000000e-01, 8.35051546e-01, 1.00000000e+00],
       [3.29694489e-02, 6.00000000e-01, 9.58762887e-01, 1.00000000e+00],
       [3.07957299e-02, 6.00000000e-01, 9.69072165e-01, 5.00000000e-01],
       [2.06990945e-02, 6.00000000e-01, 1.00000000e+00, 1.00000000e+00],
       [3.29099403e-02, 6.00000000e-01, 4.89690722e-01, 5.00000000e-01],
       [3.29694489e-02, 6.00000000e-01, 9.58762887e-01, 1.00000000e+00],
       [1.73970252e-01, 4.00000000e-01, 9.84536082e-01, 5.00000000e-01],
       [3.94277912e-02, 6.00000000e-01, 4.84536082e-01, 5.00000000e-01],
       [4.61357392e-03, 6.00000000e-01, 8.60824742e-01, 5.00000000e-01],
       [8.36658655e-02, 1.00000000e+00, 4.94845361e-01, 5.00000000e-01],
       [1.37531118e-02, 4.00000000e-01, 2.06185567e-02, 5.00000000e-01],
       [2.06990945e-02, 6.00000000e-01, 1.00000000e+00, 1.00000000e+00],
       [2.70698268e-02, 6.00000000e-01, 6.39175258e-01, 5.00000000e-01],
       [2.73111675e-02, 8.00000000e-01, 2.08762887e-01, 5.00000000e-01],
       [2.88616986e-02, 6.00000000e-01, 8.96907216e-01, 1.00000000e+00],
       [2.49175970e-02, 8.00000000e-01, 7.68041237e-01, 7.50000000e-01],
       [1.52722356e-02, 6.00000000e-01, 7.93814433e-01, 5.00000000e-01],
       [3.29099403e-02, 6.00000000e-01, 4.89690722e-01, 5.00000000e-01],
       [2.36695683e-02, 6.00000000e-01, 1.00000000e+00, 7.50000000e-01],
       [8.80562820e-03, 6.00000000e-01, 7.68041237e-01, 7.50000000e-01],
       [4.01584253e-02, 6.00000000e-01, 4.84536082e-01, 1.00000000e+00],
       [4.56133855e-02, 6.00000000e-01, 1.00000000e+00, 5.00000000e-01],
       [2.53473818e-02, 6.00000000e-01, 6.90721649e-01, 1.00000000e+00],
       [2.06990945e-02, 6.00000000e-01, 1.00000000e+00, 1.00000000e+00],
       [1.59086476e-02, 6.00000000e-01, 7.93814433e-01, 7.50000000e-01],
       [3.22669162e-03, 6.00000000e-01, 7.86082474e-01, 7.50000000e-01],
       [1.02702024e-02, 6.00000000e-01, 8.19587629e-01, 7.50000000e-01],
       [1.85931492e-02, 6.00000000e-01, 7.31958763e-01, 7.50000000e-01],
       [2.28777725e-03, 6.00000000e-01, 8.71134021e-01, 1.00000000e+00],
       [2.07238898e-02, 6.00000000e-01, 1.00000000e+00, 5.00000000e-01],
       [8.64197939e-03, 6.00000000e-01, 3.55670103e-01, 5.00000000e-01],
       [3.29694489e-02, 6.00000000e-01, 9.58762887e-01, 1.00000000e+00],
       [3.29694489e-02, 6.00000000e-01, 9.58762887e-01, 1.00000000e+00],
       [3.29099403e-02, 6.00000000e-01, 4.89690722e-01, 5.00000000e-01],
       [4.61357392e-03, 6.00000000e-01, 8.60824742e-01, 5.00000000e-01],
       [2.38464412e-02, 6.00000000e-01, 9.48453608e-01, 5.00000000e-01],
       [2.17553731e-02, 6.00000000e-01, 6.64948454e-01, 5.00000000e-01],
       [1.31216588e-02, 6.00000000e-01, 7.42268041e-01, 5.00000000e-01],
       [1.59086476e-02, 6.00000000e-01, 7.93814433e-01, 7.50000000e-01],
       [3.29099403e-02, 6.00000000e-01, 4.89690722e-01, 5.00000000e-01],
       [1.00000000e+00, 1.00000000e+00, 4.94845361e-01, 5.00000000e-01],
       [8.36658655e-02, 1.00000000e+00, 4.94845361e-01, 5.00000000e-01],
       [2.88616986e-02, 6.00000000e-01, 8.96907216e-01, 1.00000000e+00],
       [3.29099403e-02, 6.00000000e-01, 4.89690722e-01, 5.00000000e-01],
       [2.66268179e-02, 6.00000000e-01, 7.42268041e-01, 7.50000000e-01],
       [9.55279244e-03, 6.00000000e-01, 1.00000000e+00, 7.50000000e-01],
       [3.29694489e-02, 6.00000000e-01, 9.58762887e-01, 1.00000000e+00],
       [9.81744066e-02, 4.00000000e-01, 9.89690722e-01, 5.00000000e-01],
       [6.23386241e-02, 6.00000000e-01, 9.43298969e-01, 7.50000000e-01],
       [1.14058259e-04, 6.00000000e-01, 1.00000000e+00, 7.50000000e-01],
       [3.11296396e-02, 6.00000000e-01, 9.17525773e-01, 7.50000000e-01],
       [8.36658655e-02, 1.00000000e+00, 4.94845361e-01, 5.00000000e-01],
       [7.81596617e-02, 4.00000000e-01, 1.00000000e+00, 5.00000000e-01],
       [8.36658655e-02, 1.00000000e+00, 4.94845361e-01, 5.00000000e-01],
       [9.15276203e-02, 1.00000000e+00, 8.96907216e-01, 5.00000000e-01],
       [1.97453029e-02, 6.00000000e-01, 8.19587629e-01, 7.50000000e-01],
       [6.80514552e-02, 1.00000000e+00, 7.93814433e-01, 5.00000000e-01],
       [3.57878450e-03, 6.00000000e-01, 7.93814433e-01, 5.00000000e-01],
       [2.33042512e-02, 6.00000000e-01, 2.26804124e-01, 5.00000000e-01],
       [3.29694489e-02, 6.00000000e-01, 9.58762887e-01, 1.00000000e+00],
       [9.55279244e-03, 6.00000000e-01, 1.00000000e+00, 7.50000000e-01],
       [2.06990945e-02, 6.00000000e-01, 1.00000000e+00, 1.00000000e+00],
       [3.80276847e-02, 6.00000000e-01, 7.75773196e-01, 2.50000000e-01],
       [9.91480344e-03, 6.00000000e-01, 1.00000000e+00, 5.00000000e-01],
       [6.36511206e-02, 4.00000000e-01, 4.94845361e-01, 5.00000000e-01],
       [3.29099403e-02, 6.00000000e-01, 4.89690722e-01, 5.00000000e-01],
       [3.82442301e-02, 6.00000000e-01, 6.70103093e-01, 5.00000000e-01],
       [2.88616986e-02, 6.00000000e-01, 8.96907216e-01, 1.00000000e+00],
       [9.81744066e-02, 4.00000000e-01, 9.89690722e-01, 5.00000000e-01],
       [4.40711195e-02, 8.00000000e-01, 8.71134021e-01, 1.00000000e+00],
       [2.74566331e-02, 6.00000000e-01, 1.00000000e+00, 7.50000000e-01],
       [2.67722835e-02, 4.00000000e-01, 8.99484536e-01, 7.50000000e-01],
       [3.29099403e-02, 6.00000000e-01, 4.89690722e-01, 5.00000000e-01],
       [9.42881608e-03, 4.00000000e-01, 5.64432990e-01, 5.00000000e-01],
       [4.61357392e-03, 6.00000000e-01, 8.60824742e-01, 5.00000000e-01],
       [3.57878450e-03, 6.00000000e-01, 7.93814433e-01, 5.00000000e-01],
       [1.32472882e-02, 6.00000000e-01, 8.06701031e-01, 5.00000000e-01],
       [2.86616834e-02, 6.00000000e-01, 1.00000000e+00, 5.00000000e-01],
       [2.42696139e-02, 6.00000000e-01, 8.19587629e-01, 7.50000000e-01],
       [3.41893764e-02, 8.00000000e-01, 9.02061856e-01, 7.50000000e-01],
       [2.36695683e-02, 6.00000000e-01, 1.00000000e+00, 7.50000000e-01],
       [2.06990945e-02, 6.00000000e-01, 1.00000000e+00, 1.00000000e+00],
       [1.16389015e-02, 6.00000000e-01, 9.51030928e-01, 7.50000000e-01],
       [2.96072098e-02, 6.00000000e-01, 9.04639175e-01, 5.00000000e-01],
       [2.06990945e-02, 6.00000000e-01, 1.00000000e+00, 1.00000000e+00],
       [2.88616986e-02, 6.00000000e-01, 8.96907216e-01, 1.00000000e+00],
       [1.15893109e-02, 6.00000000e-01, 1.00000000e+00, 5.00000000e-01],
       [1.13628474e-02, 0.00000000e+00, 1.00000000e+00, 5.00000000e-01],
       [1.00262169e-01, 4.00000000e-01, 6.77835052e-01, 5.00000000e-01],
       [9.81744066e-02, 4.00000000e-01, 9.89690722e-01, 5.00000000e-01],
       [6.03979807e-02, 4.00000000e-01, 7.68041237e-01, 1.00000000e+00],
       [8.48328964e-03, 4.00000000e-01, 1.00000000e+00, 1.00000000e+00],
       [2.06990945e-02, 6.00000000e-01, 1.00000000e+00, 1.00000000e+00],
       [3.65812938e-02, 6.00000000e-01, 7.68041237e-01, 7.50000000e-01],
       [3.29694489e-02, 6.00000000e-01, 9.58762887e-01, 1.00000000e+00],
       [7.53411003e-01, 6.00000000e-01, 1.00000000e+00, 7.50000000e-01],
       [9.81744066e-02, 4.00000000e-01, 9.89690722e-01, 5.00000000e-01],
       [1.76476228e-02, 6.00000000e-01, 1.00000000e+00, 7.50000000e-01],
       [4.53158422e-02, 6.00000000e-01, 9.22680412e-01, 5.00000000e-01],
       [2.67722835e-02, 6.00000000e-01, 7.68041237e-01, 5.00000000e-01],
       [9.55279244e-03, 6.00000000e-01, 1.00000000e+00, 7.50000000e-01],
       [2.36695683e-02, 6.00000000e-01, 1.00000000e+00, 7.50000000e-01],
       [3.04221478e-02, 6.00000000e-01, 7.42268041e-01, 5.00000000e-01],
       [3.29099403e-02, 6.00000000e-01, 4.89690722e-01, 5.00000000e-01],
       [9.55279244e-03, 6.00000000e-01, 1.00000000e+00, 7.50000000e-01],
       [3.14255299e-02, 6.00000000e-01, 1.13402062e-01, 1.00000000e+00],
       [8.98580719e-03, 6.00000000e-01, 5.02577320e-01, 7.50000000e-01],
       [7.81381725e-03, 6.00000000e-01, 8.19587629e-01, 1.00000000e+00],
       [2.36695683e-02, 6.00000000e-01, 1.00000000e+00, 7.50000000e-01],
       [3.91434721e-03, 6.00000000e-01, 1.00000000e+00, 5.00000000e-01],
       [3.29694489e-02, 6.00000000e-01, 9.58762887e-01, 1.00000000e+00],
       [1.83534616e-02, 6.00000000e-01, 7.73195876e-01, 1.00000000e+00]])